#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import setuptools
setuptools.setup(name="atac_module",
                 version="0.1.0",
                 author="Benjamin James",
                 author_email="benjames@mit.edu",
                 url="https://github.com/KellisLab/atac_module",
                 license="GPL",
                 install_requires=[
                     "numpy",
                     "scipy",
                     "sklearn",
                     "numba",
                     "anndata>=0.8.0",
                     "pandas",
                     "umap-learn",
                     "pynndescent>=0.5.7",
                     "scanpy",
                     "matplotlib",
                     "seaborn",
                     "python-igraph",
                     "leidenalg",
                     "tqdm",
                     "infomap>=2.5.0",
                     "pyranges",
                 ],
                 packages=setuptools.find_packages("."),
                 test_suite="test",
                 # scripts=["scripts/atac_module_compute_cor.py"],
                 )
