name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Check conda
      run: |
          echo ${CONDA}
          ${CONDA}/bin/conda --version
    - name: Install dependencies
      run: |
        conda env update --file epiclust.yml --name base
    - name: Install pylint
      run: |
        conda install pylint
    - name: Analyze the code with pylint
      run: |
        pylint --rcfile=.pylintrc --fail-under 6 $(git ls-files '*.py')
